apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: e2e-tests-pipeline
  annotations:
    pipelinesascode.tekton.dev/task: "[tasks/e2e-test.yaml]"
spec:
  params:
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      default: ''
      type: string
    - name: repo_url
      value: "{{ repo_url }}"
      default: "default_repo_url_value"
    - name: revision
      value: "{{ revision }}"
      default: "default_revision_value"
    - name: e2e_test_namespace
      value: build-templates-e2e
      default: "default_e2e_tests_namespace_value"
  tasks:
    - name: prepare-e2e-tests
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
      taskSpec:
        params:
        - name: SNAPSHOT
        steps:
          - name: e2e-tests
            image: quay.io/redhat-appstudio/appstudio-utils:f58ba64422b4d9bbcb4b296fbfe7b60f7793c3c1
            env:
            - name: SNAPSHOT
              value: $(params.SNAPSHOT)
            script: |
              echo "Preparing to run the e2e-tests"
              echo "Got SS: ${SNAPSHOT}"
              SOURCE_IMAGE=$(echo -n ${SNAPSHOT} | jq -r .components[0].containerImage)
              echo "Built image: ${SOURCE_IMAGE}"
    - name: run-e2e-tests
      params:
        - name: e2e_test_namespace
          value: $(params.e2e_test_namespace)
        - name: app_suffix
          value: "app-integration"
        - name: ec_pipelines_repo_url
          value: "{{ source_url }}"
        - name: ec_pipelines_repo_revision
          value: "{{ revision }}"
      runAfter:
        - prepare-e2e-tests
      taskRef:
        name: e2e-test
      # Added a timeout due to https://issues.redhat.com/browse/STONEBLD-2265
      timeout: "2h"



