apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: e2e-tests-pipeline
spec:
  params:
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      default: ''
      type: string
  tasks:
    - name: e2e-tests-task
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
      taskSpec:
        params:
        - name: SNAPSHOT
        steps:
          - name: e2e-tests
            image: registry.redhat.io/openshift4/ose-cli:latest
            env:
            - name: SNAPSHOT
              value: $(params.SNAPSHOT)
            script: |
              echo "Running the e2e-tests"
              echo "Got SS: ${SNAPSHOT}"
              BUILT_IMAGE=$(echo -n ${SNAPSHOT} | jq -r .components[0].containerImage)
              echo "Built image: ${BUILT_IMAGE}"


