apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: e2e-tests-pipeline
spec:
  params:
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      default: ''
      type: string
    - name: repo_url
      value: "{{ repo_url }}"
      default: ""
    - name: revision
      value: "{{ revision }}"
      default: ""
    - name: e2e_test_namespace
      value: build-templates-e2e
      default: ""
  tasks:
    - name: prepare-e2e-tests
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: e2e_test_namespace
          value: $(params.e2e_test_namespace)
        - name: repo_url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
      taskSpec:
        params:
        - name: SNAPSHOT
        steps:
          - name: e2e-tests
            image: quay.io/susdas/appstudio-utils:with-make
            env:
            - name: SNAPSHOT
              value: $(params.SNAPSHOT)
            # - name: QUAY_TOKEN
            #   valueFrom:
            #     secretKeyRef:
            #       name: quay-token
            #       key: token
            script: |
              echo "Preparing to run the e2e-tests"
              echo "Got SS: ${SNAPSHOT}"
              export SOURCE_IMAGE=$(echo -n ${SNAPSHOT} | jq -r .components[0].containerImage)
              echo "Built image: ${SOURCE_IMAGE}"
              
              git clone --branch setup-source-build https://github.com/tisutisu/e2e-tests.git
              cd e2e-tests/
              make setup-source-build

              # Debug command
              oc whoami
              oc get pods
            
            volumeMounts:
              - mountPath: /root/.docker/config.json
                subPath: .dockerconfigjson
                name: quay-secret
        volumes:
          - name: quay-secret
            secret:
              secretName: quay-token

    - name: run-e2e-tests
      params:
        - name: e2e_test_namespace
          value: "build-templates-e2e"
        - name: app_suffix
          value: "app-intergration"
        - name: ec_pipelines_repo_url
          value: "https://github.com/redhat-appstudio/build-definitions.git"
        - name: ec_pipelines_repo_revision
          value: "main"
      runAfter:
        - prepare-e2e-tests
      taskRef:
        resolver: git
        params:
          - name: url
            value: "https://github.com/tisutisu/integration-tests.git"
          - name: revision
            value: "main"
          - name: pathInRepo
            value: tasks/e2e-test.yaml
      # Added a timeout due to https://issues.redhat.com/browse/STONEBLD-2265
      timeout: "2h"



