apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: e2e-tests-pipeline
spec:
  params:
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      type: string
  tasks:
    - name: e2e-tests-task
      taskSpec:
        params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        steps:
          - name: e2e-tests
            image: alpine
            env:
            - name: SNAPSHOT
              value: $(params.SNAPSHOT)
            script: |
              echo "Running the e2e-tests"
              echo "Got SS: ${SNAPSHOT}"


