apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: e2e-tests-pipeline
spec:
  params:
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
  tasks:
    - name: e2e-tests-task
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
      taskSpec:
        steps:
          - name: e2e-tests
            image: alpine
            env:
            - name: SNAPSHOT
              value: $(params.SNAPSHOT)
            script: |
              echo "Running the e2e-tests"
              echo "Got SS: ${SNAPSHOT}"


